import {
  DatabaseIcon,
  FileArchiveIcon,
  FileAxis3dIcon,
  FileBoxIcon,
  FileBracesIcon,
  FileChartColumnIcon,
  FileCodeIcon,
  FileCogIcon,
  FileDiffIcon,
  FileIcon,
  FileImageIcon,
  FileJsonIcon,
  FileKeyIcon,
  FileLockIcon,
  FileMusicIcon,
  FileSlidersIcon,
  FileSpreadsheetIcon,
  FileTerminalIcon,
  FileTextIcon,
  FileTypeIcon,
  FileVideoIcon,
  type LucideIcon,
} from "lucide-react";

const FILE_ICON_BY_NAME: Record<string, LucideIcon> = {
  ".babelrc": FileSlidersIcon,
  ".dockerignore": FileSlidersIcon,
  ".editorconfig": FileSlidersIcon,
  ".eslintrc": FileSlidersIcon,
  ".eslintrc.cjs": FileSlidersIcon,
  ".eslintrc.js": FileSlidersIcon,
  ".eslintrc.json": FileJsonIcon,
  ".eslintrc.yaml": FileSlidersIcon,
  ".eslintrc.yml": FileSlidersIcon,
  ".gitattributes": FileSlidersIcon,
  ".gitignore": FileSlidersIcon,
  ".npmrc": FileSlidersIcon,
  ".prettierrc": FileSlidersIcon,
  ".prettierrc.json": FileJsonIcon,
  ".prettierrc.yaml": FileSlidersIcon,
  ".prettierrc.yml": FileSlidersIcon,
  "agents.md": FileTextIcon,
  authors: FileTextIcon,
  "bun.lock": FileBoxIcon,
  "bun.lockb": FileBoxIcon,
  "cargo.lock": FileBoxIcon,
  "cargo.toml": FileBoxIcon,
  changelog: FileTextIcon,
  "changelog.md": FileTextIcon,
  "cmakelists.txt": FileCogIcon,
  codeowners: FileKeyIcon,
  "components.json": FileSlidersIcon,
  "composer.json": FileBoxIcon,
  "composer.lock": FileBoxIcon,
  contributing: FileTextIcon,
  "contributing.md": FileTextIcon,
  copying: FileKeyIcon,
  dockerfile: FileCogIcon,
  gemfile: FileBoxIcon,
  "go.mod": FileBoxIcon,
  "go.sum": FileBoxIcon,
  license: FileKeyIcon,
  makefile: FileTerminalIcon,
  "meson.build": FileCogIcon,
  notice: FileKeyIcon,
  "package-lock.json": FileBoxIcon,
  "package.json": FileBoxIcon,
  pipfile: FileBoxIcon,
  "pnpm-lock.yaml": FileBoxIcon,
  "pnpm-workspace.yaml": FileBoxIcon,
  "poetry.lock": FileBoxIcon,
  "pom.xml": FileBoxIcon,
  "postcss.config.cjs": FileSlidersIcon,
  "postcss.config.js": FileSlidersIcon,
  "postcss.config.mjs": FileSlidersIcon,
  "postcss.config.ts": FileSlidersIcon,
  "pyproject.toml": FileBoxIcon,
  readme: FileTextIcon,
  "readme.md": FileTextIcon,
  "requirements-dev.txt": FileBoxIcon,
  "requirements.txt": FileBoxIcon,
  security: FileLockIcon,
  "security.md": FileLockIcon,
  "settings.gradle": FileCogIcon,
  "settings.gradle.kts": FileCogIcon,
  "tailwind.config.cjs": FileSlidersIcon,
  "tailwind.config.js": FileSlidersIcon,
  "tailwind.config.mjs": FileSlidersIcon,
  "tailwind.config.ts": FileSlidersIcon,
  todo: FileTextIcon,
  "tsconfig.json": FileSlidersIcon,
  "vite.config.js": FileSlidersIcon,
  "vite.config.mjs": FileSlidersIcon,
  "vite.config.ts": FileSlidersIcon,
  "vitest.config.js": FileSlidersIcon,
  "vitest.config.mjs": FileSlidersIcon,
  "vitest.config.ts": FileSlidersIcon,
  "yarn.lock": FileBoxIcon,
};

const FILE_ICON_BY_EXTENSION: Record<string, LucideIcon> = {
  "7z": FileArchiveIcon,
  aac: FileMusicIcon,
  adoc: FileTextIcon,
  ai: FileImageIcon,
  asc: FileKeyIcon,
  astro: FileCodeIcon,
  avi: FileVideoIcon,
  avif: FileImageIcon,
  bash: FileTerminalIcon,
  bat: FileTerminalIcon,
  blend: FileAxis3dIcon,
  bmp: FileImageIcon,
  br: FileArchiveIcon,
  bz2: FileArchiveIcon,
  c: FileCodeIcon,
  cc: FileCodeIcon,
  cer: FileKeyIcon,
  cfg: FileSlidersIcon,
  cjs: FileCodeIcon,
  clj: FileCodeIcon,
  cmd: FileTerminalIcon,
  conf: FileSlidersIcon,
  cpp: FileCodeIcon,
  crt: FileKeyIcon,
  cs: FileCodeIcon,
  css: FileTypeIcon,
  csv: FileSpreadsheetIcon,
  cts: FileCodeIcon,
  cxx: FileCodeIcon,
  dart: FileCodeIcon,
  db: DatabaseIcon,
  diff: FileDiffIcon,
  dmg: FileArchiveIcon,
  doc: FileTextIcon,
  docx: FileTextIcon,
  duckdb: DatabaseIcon,
  eot: FileTypeIcon,
  eps: FileImageIcon,
  erl: FileCodeIcon,
  ex: FileCodeIcon,
  exs: FileCodeIcon,
  fbx: FileAxis3dIcon,
  fish: FileTerminalIcon,
  flac: FileMusicIcon,
  fs: FileCodeIcon,
  fsx: FileCodeIcon,
  gif: FileImageIcon,
  glb: FileAxis3dIcon,
  gltf: FileAxis3dIcon,
  go: FileCodeIcon,
  gpg: FileKeyIcon,
  gql: FileBracesIcon,
  gradle: FileCogIcon,
  graphql: FileBracesIcon,
  gz: FileArchiveIcon,
  h: FileCodeIcon,
  hcl: FileSlidersIcon,
  heic: FileImageIcon,
  hpp: FileCodeIcon,
  hrl: FileCodeIcon,
  hs: FileCodeIcon,
  htm: FileCodeIcon,
  html: FileCodeIcon,
  ico: FileImageIcon,
  ini: FileSlidersIcon,
  ipynb: FileChartColumnIcon,
  iso: FileArchiveIcon,
  java: FileCodeIcon,
  jpeg: FileImageIcon,
  jpg: FileImageIcon,
  js: FileCodeIcon,
  json: FileJsonIcon,
  json5: FileJsonIcon,
  jsonc: FileJsonIcon,
  jsx: FileCodeIcon,
  key: FileKeyIcon,
  kt: FileCodeIcon,
  kts: FileCodeIcon,
  less: FileTypeIcon,
  lock: FileLockIcon,
  log: FileTextIcon,
  lua: FileCodeIcon,
  m4a: FileMusicIcon,
  m4v: FileVideoIcon,
  md: FileTextIcon,
  mdx: FileTextIcon,
  mjs: FileCodeIcon,
  mkv: FileVideoIcon,
  mmd: FileChartColumnIcon,
  mov: FileVideoIcon,
  mp3: FileMusicIcon,
  mp4: FileVideoIcon,
  mpeg: FileVideoIcon,
  mpg: FileVideoIcon,
  mts: FileCodeIcon,
  nim: FileCodeIcon,
  nu: FileTerminalIcon,
  obj: FileAxis3dIcon,
  ods: FileSpreadsheetIcon,
  ogg: FileMusicIcon,
  opus: FileMusicIcon,
  otf: FileTypeIcon,
  p12: FileLockIcon,
  patch: FileDiffIcon,
  pdf: FileTextIcon,
  pem: FileKeyIcon,
  pfx: FileLockIcon,
  php: FileCodeIcon,
  pl: FileCodeIcon,
  pm: FileCodeIcon,
  png: FileImageIcon,
  ppt: FileChartColumnIcon,
  pptx: FileChartColumnIcon,
  prisma: DatabaseIcon,
  properties: FileSlidersIcon,
  proto: FileBracesIcon,
  ps1: FileTerminalIcon,
  psd: FileImageIcon,
  pub: FileKeyIcon,
  py: FileCodeIcon,
  r: FileCodeIcon,
  rar: FileArchiveIcon,
  rb: FileCodeIcon,
  rst: FileTextIcon,
  rs: FileCodeIcon,
  rtf: FileTextIcon,
  sass: FileTypeIcon,
  scala: FileCodeIcon,
  scss: FileTypeIcon,
  sh: FileTerminalIcon,
  sol: FileCodeIcon,
  sqlite: DatabaseIcon,
  sqlite3: DatabaseIcon,
  sql: DatabaseIcon,
  stl: FileAxis3dIcon,
  svelte: FileCodeIcon,
  svg: FileImageIcon,
  swift: FileCodeIcon,
  tar: FileArchiveIcon,
  "tar.bz2": FileArchiveIcon,
  "tar.gz": FileArchiveIcon,
  "tar.xz": FileArchiveIcon,
  tbz2: FileArchiveIcon,
  tex: FileTextIcon,
  tf: FileSlidersIcon,
  tfvars: FileSlidersIcon,
  tgz: FileArchiveIcon,
  tif: FileImageIcon,
  tiff: FileImageIcon,
  toml: FileSlidersIcon,
  ts: FileCodeIcon,
  tsx: FileCodeIcon,
  tsv: FileSpreadsheetIcon,
  ttf: FileTypeIcon,
  txt: FileTextIcon,
  txz: FileArchiveIcon,
  vb: FileCodeIcon,
  vue: FileCodeIcon,
  wav: FileMusicIcon,
  webm: FileVideoIcon,
  webp: FileImageIcon,
  woff: FileTypeIcon,
  woff2: FileTypeIcon,
  xhtml: FileCodeIcon,
  xls: FileSpreadsheetIcon,
  xlsx: FileSpreadsheetIcon,
  xml: FileCodeIcon,
  xz: FileArchiveIcon,
  yaml: FileSlidersIcon,
  yml: FileSlidersIcon,
  zig: FileCodeIcon,
  zip: FileArchiveIcon,
  zsh: FileTerminalIcon,
};

const COMPOUND_EXTENSIONS = ["tar.bz2", "tar.gz", "tar.xz"] as const;

function getFilename(filePath: string): string {
  const lastSlash = Math.max(filePath.lastIndexOf("/"), filePath.lastIndexOf("\\"));
  return lastSlash >= 0 ? filePath.slice(lastSlash + 1) : filePath;
}

function getExtension(filename: string): string {
  const lowerName = filename.toLowerCase();
  const compoundExtension = COMPOUND_EXTENSIONS.find((extension) =>
    lowerName.endsWith(`.${extension}`),
  );
  if (compoundExtension) {
    return compoundExtension;
  }

  const lastDot = filename.lastIndexOf(".");
  if (lastDot <= 0 || lastDot === filename.length - 1) {
    return "";
  }

  return filename.slice(lastDot + 1).toLowerCase();
}

export function getFileTypeIcon(filePath: string): LucideIcon {
  const filename = getFilename(filePath);
  const lowerName = filename.toLowerCase();
  const exactMatch = FILE_ICON_BY_NAME[lowerName];
  if (exactMatch) {
    return exactMatch;
  }

  if (lowerName === ".env" || lowerName.startsWith(".env.")) {
    return FileLockIcon;
  }

  if (lowerName === "dockerfile" || lowerName.startsWith("dockerfile.")) {
    return FileCogIcon;
  }

  if (lowerName === "makefile" || lowerName.startsWith("makefile.")) {
    return FileTerminalIcon;
  }

  return FILE_ICON_BY_EXTENSION[getExtension(filename)] ?? FileIcon;
}
